[package]
name = "metap-app"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-cache = { path = "../metap-cache", features = ["redis-backend"] }
metap-control = { path = "../metap-control" }
metap-infra = { path = "../metap-infra" }
metap-permission = { path = "../metap-permission" }
anyhow.workspace = true
jsonwebtoken.workspace = true
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls"] }
tracing.workspace = true
