[package]
name = "metap-auth"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
metap-peripherals = { path = "../metap-peripherals" }
openidconnect = { version = "4", default-features = false, features = ["reqwest"] }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "json",
] }
uuid.workspace = true

[dev-dependencies]
base64.workspace = true
jsonwebtoken.workspace = true
rand = "0.8"
rsa = { version = "0.9", features = ["pem"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
wiremock = "0.6"
