[package]
name = "metap-graphql-http"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-crud = { path = "../metap-crud" }
metap-graphql = { path = "../metap-graphql" }
metap-http = { path = "../metap-http" }
metap-metadata = { path = "../metap-metadata" }
anyhow.workspace = true
async-graphql.workspace = true
async-graphql-axum = "7"
axum.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
arc-swap.workspace = true
metap-control = { path = "../metap-control" }
metap-peripherals = { path = "../metap-peripherals" }
metap-permission = { path = "../metap-permission" }
jsonwebtoken.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
uuid.workspace = true
