[package]
name = "metap-jwks"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-runtime = { path = "../metap-runtime" }
metap-peripherals = { path = "../metap-peripherals" }
anyhow.workspace = true
base64.workspace = true
jsonwebtoken.workspace = true
moka.workspace = true
reqwest.workspace = true
ring = "0.17"
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
wiremock = "0.6"
