[package]
name = "metap-config"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
moka.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls", "json", "chrono", "uuid"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
