[package]
name = "metap-graphql-gateway"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "graphql-gateway"
path = "src/main.rs"

[dependencies]
metap-runtime = { path = "../metap-runtime" }
metap-crud = { path = "../metap-crud" }
metap-graphql = { path = "../metap-graphql" }
metap-graphql-http = { path = "../metap-graphql-http" }
metap-grpc = { path = "../metap-grpc" }
metap-http = { path = "../metap-http" }
metap-infra = { path = "../metap-infra" }
metap-metadata = { path = "../metap-metadata" }
metap-peripherals = { path = "../metap-peripherals" }
metap-permission = { path = "../metap-permission" }
anyhow.workspace = true
async-graphql.workspace = true
async-graphql-axum = "7"
axum.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing.workspace = true

[dev-dependencies]
arc-swap.workspace = true
metap-control = { path = "../metap-control" }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }
uuid.workspace = true
