[package]
name = "metap-query"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-metadata = { path = "../metap-metadata" }
metap-permission = { path = "../metap-permission" }
anyhow.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "chrono",
  "json",
] }
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
async-trait.workspace = true
criterion = "0.5"

[[bench]]
name = "plan_list_bench"
harness = false
