[package]
name = "metap-peripherals"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-metadata = { path = "../metap-metadata" }
anyhow.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "chrono",
] }
uuid.workspace = true
tracing.workspace = true
argon2 = { version = "0.5", features = ["password-hash"] }
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
