[package]
name = "metap-notification-worker"
version = "0.1.0"
edition.workspace = true

[lib]
name = "notification_worker"
path = "src/lib.rs"

[[bin]]
name = "notification-worker"
path = "src/main.rs"

[dependencies]
metap-runtime = { path = "../metap-runtime" }
metap-infra = { path = "../metap-infra" }
anyhow.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
futures-util.workspace = true
tracing.workspace = true
