[package]
name = "metap-workflow"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-infra = { path = "../metap-infra" }
metap-metadata = { path = "../metap-metadata" }
metap-permission = { path = "../metap-permission" }
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "chrono",
  "json",
  "macros",
] }
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
