//! Cookie-based session issuance for browser callers, added alongside (not instead of) the
//! existing Bearer/Basic flows in `crate::auth`. Trigger: `docs/roadmap.md` Phase 63's audit
//! found the JWT living only in `@metap/platform-ui`'s React state — lost on every page
//! reload, previously a deliberate tradeoff (`CLAUDE.md`), revisited by the project owner.
//!
//! Two cookies are set together, both scoped `Path=/`:
//! - [`SESSION_COOKIE_NAME`] — the JWT itself, `HttpOnly` so page script can never read it
//!   (the whole point of moving off JS-held state: an XSS payload can no longer exfiltrate the
//!   session token).
//! - [`CSRF_COOKIE_NAME`] — a random value, deliberately **not** `HttpOnly`. A cookie a browser
//!   attaches automatically is exactly what a cross-site form/script can trigger without ever
//!   reading it; the double-submit pattern used here (`crate::auth::AuthContext` requires the
//!   [`CSRF_HEADER_NAME`] header to echo this cookie's value on any state-changing request) relies
//!   on same-origin JS being the only thing that *can* read it to echo it back — a forged
//!   cross-origin request can make the browser attach the cookie but can't read its value to put
//!   in a header.
//!
//! Both live entirely alongside the Bearer/Basic flows: a caller that never sends a session
//! cookie (a CLI, a service using `dev-tools mint-token`'s output, another `metap` service
//! forwarding a caller's Bearer token) is completely unaffected — see `crate::auth`'s extractor,
//! which only falls back to the cookie once no `Authorization` header is present at all.

use axum_extra::extract::cookie::{Cookie, SameSite};
use time::Duration;

pub const SESSION_COOKIE_NAME: &str = "metap_session";
pub const CSRF_COOKIE_NAME: &str = "metap_csrf";
/// Request header a browser client must echo the [`CSRF_COOKIE_NAME`] cookie's value into for any
/// state-changing (non-GET/HEAD/OPTIONS) cookie-authenticated request — see this module's own doc
/// comment for why. Lowercase: `HeaderName` comparison is case-insensitive regardless, lowercase
/// is just this crate's own convention for header name constants (see `x-tenant-id` in
/// `crate::auth::basic_auth`).
pub const CSRF_HEADER_NAME: &str = "x-csrf-token";

/// `SameSite=Lax` rather than `Strict`: `Strict` withholds the cookie even on a plain top-level
/// navigation *into* the app from an external link (e.g. a bookmarked page, or a link from an
/// email), which would silently look like "not logged in" instead of an actual security boundary
/// — `Lax` still blocks the cross-site POST/fetch shapes CSRF actually depends on. Combined with
/// the CSRF double-submit check above, not relied on alone.
fn base_cookie(name: &'static str, value: String, http_only: bool, secure: bool, max_age: Duration) -> Cookie<'static> {
    Cookie::build((name, value))
        .path("/")
        .same_site(SameSite::Lax)
        .secure(secure)
        .http_only(http_only)
        .max_age(max_age)
        .build()
}

/// Builds the pair of `Set-Cookie` values a successful login (local or OIDC) issues. `csrf_value`
/// is generated by the caller (a fresh random value per login — `routes::auth` uses a UUID v4,
/// already an OS-RNG-backed dependency this crate carries for other IDs, not worth adding a
/// second randomness source for one more token) rather than derived from the JWT, so a leaked JWT
/// alone (e.g. via a server log that shouldn't have captured it) still isn't enough to forge the
/// CSRF header — the two secrets are independent.
pub fn session_cookies(
    token: &str,
    csrf_value: &str,
    ttl_seconds: i64,
    secure: bool,
) -> (Cookie<'static>, Cookie<'static>) {
    let max_age = Duration::seconds(ttl_seconds);
    let session = base_cookie(SESSION_COOKIE_NAME, token.to_string(), true, secure, max_age);
    let csrf = base_cookie(CSRF_COOKIE_NAME, csrf_value.to_string(), false, secure, max_age);
    (session, csrf)
}

/// `POST /auth/logout`'s pair — `Max-Age(0)` (rather than omitting `Max-Age`, which would create
/// a *session* cookie instead of deleting the existing persistent one) tells the browser to expire
/// the cookie immediately. Attributes (`Path`/`SameSite`/`Secure`) must match the ones the cookie
/// was originally set with, or the browser treats this as a different cookie and the original
/// persists — `secure` is threaded through for exactly that reason.
pub fn clear_session_cookies(secure: bool) -> (Cookie<'static>, Cookie<'static>) {
    let expire = Duration::seconds(0);
    let session = base_cookie(SESSION_COOKIE_NAME, String::new(), true, secure, expire);
    let csrf = base_cookie(CSRF_COOKIE_NAME, String::new(), false, secure, expire);
    (session, csrf)
}
