//! Cookie-based session issuance for browser callers, added alongside (not instead of) the
//! existing Bearer/Basic flows in `crate::auth`. Trigger: `docs/roadmap.md` Phase 63's audit
//! found the JWT living only in `@metap/platform-ui`'s React state — lost on every page
//! reload, previously a deliberate tradeoff (`CLAUDE.md`), revisited by the project owner.
//!
//! Two cookies are set together, both scoped `Path=/`:
//! - [`SESSION_COOKIE_NAME`] — the JWT itself, `HttpOnly` so page script can never read it
//!   (the whole point of moving off JS-held state: an XSS payload can no longer exfiltrate the
//!   session token).
//! - [`CSRF_COOKIE_NAME`] — a random value, deliberately **not** `HttpOnly`. A cookie a browser
//!   attaches automatically is exactly what a cross-site form/script can trigger without ever
//!   reading it; the double-submit pattern used here (`crate::auth::AuthContext` requires the
//!   [`CSRF_HEADER_NAME`] header to echo this cookie's value on any state-changing request) relies
//!   on same-origin JS being the only thing that *can* read it to echo it back — a forged
//!   cross-origin request can make the browser attach the cookie but can't read its value to put
//!   in a header.
//!
//! Both live entirely alongside the Bearer/Basic flows: a caller that never sends a session
//! cookie (a CLI, a service using `dev-tools mint-token`'s output, another `metap` service
//! forwarding a caller's Bearer token) is completely unaffected — see `crate::auth`'s extractor,
//! which only falls back to the cookie once no `Authorization` header is present at all.

use axum_extra::extract::cookie::{Cookie, SameSite};
use time::Duration;

// Re-exported (not just used) so an existing `use metap_http::cookies::SESSION_COOKIE_NAME` (etc.)
// keeps compiling unchanged now that the definitions live in `metap-runtime`, shared with
// `crates/graphql-gateway` — see that module's doc comment for why it moved.
pub use metap_runtime::cookie_auth::{csrf_matches, requires_csrf_check, CSRF_COOKIE_NAME, CSRF_HEADER_NAME, SESSION_COOKIE_NAME};

/// `SameSite=Lax` rather than `Strict`: `Strict` withholds the cookie even on a plain top-level
/// navigation *into* the app from an external link (e.g. a bookmarked page, or a link from an
/// email), which would silently look like "not logged in" instead of an actual security boundary
/// — `Lax` still blocks the cross-site POST/fetch shapes CSRF actually depends on. Combined with
/// the CSRF double-submit check above, not relied on alone.
fn base_cookie(name: &'static str, value: String, http_only: bool, secure: bool, max_age: Duration) -> Cookie<'static> {
    Cookie::build((name, value))
        .path("/")
        .same_site(SameSite::Lax)
        .secure(secure)
        .http_only(http_only)
        .max_age(max_age)
        .build()
}

/// Builds the pair of `Set-Cookie` values a successful login (local or OIDC) issues. `csrf_value`
/// is generated by the caller (a fresh random value per login — `routes::auth` uses a UUID v4,
/// already an OS-RNG-backed dependency this crate carries for other IDs, not worth adding a
/// second randomness source for one more token) rather than derived from the JWT, so a leaked JWT
/// alone (e.g. via a server log that shouldn't have captured it) still isn't enough to forge the
/// CSRF header — the two secrets are independent.
pub fn session_cookies(
    token: &str,
    csrf_value: &str,
    ttl_seconds: i64,
    secure: bool,
) -> (Cookie<'static>, Cookie<'static>) {
    let max_age = Duration::seconds(ttl_seconds);
    let session = base_cookie(SESSION_COOKIE_NAME, token.to_string(), true, secure, max_age);
    let csrf = base_cookie(CSRF_COOKIE_NAME, csrf_value.to_string(), false, secure, max_age);
    (session, csrf)
}

/// Whether a **credential-issuing** request is allowed to proceed — `GET /auth/token`'s extra gate
/// (audit 04 finding A#4, fixed 2026-09-03).
///
/// [`requires_csrf_check`] exempts `GET` because a safe method must not change state. `GET
/// /auth/token` doesn't change state either — it *mints a fresh Bearer JWT carrying the caller's
/// full identity*, which is a different kind of risk that the safe-method rule was never about.
/// Before this, the only thing stopping a foreign page from reading that token was CORS: correct
/// today (`metap_runtime::cors::build` is fail-closed with no configured origins, and only ever
/// pairs `allow_credentials` with an explicit origin list), but it made the most sensitive endpoint
/// in the app depend entirely on one env var being right and on every allowlisted origin staying
/// free of XSS. This makes the endpoint stand on its own instead.
///
/// Mirrors `crate::auth::AuthContext`'s own precedence exactly: an `Authorization` header wins and
/// is never CSRF-gated (a browser cannot attach one to a cross-site request), so only a request
/// actually authenticating *by cookie* has to present the double-submit pair.
pub fn credential_issuing_request_allowed(headers: &axum::http::HeaderMap) -> bool {
    if headers.contains_key(axum::http::header::AUTHORIZATION) {
        return true;
    }
    let jar = axum_extra::extract::cookie::CookieJar::from_headers(headers);
    if jar.get(SESSION_COOKIE_NAME).is_none() {
        // No cookie either — `AuthContext` will reject this on its own; nothing to gate here.
        return true;
    }
    csrf_matches(
        jar.get(CSRF_COOKIE_NAME).map(|c| c.value()),
        headers.get(CSRF_HEADER_NAME).and_then(|v| v.to_str().ok()),
    )
}

/// `POST /auth/logout`'s pair — `Max-Age(0)` (rather than omitting `Max-Age`, which would create
/// a *session* cookie instead of deleting the existing persistent one) tells the browser to expire
/// the cookie immediately. Attributes (`Path`/`SameSite`/`Secure`) must match the ones the cookie
/// was originally set with, or the browser treats this as a different cookie and the original
/// persists — `secure` is threaded through for exactly that reason.
pub fn clear_session_cookies(secure: bool) -> (Cookie<'static>, Cookie<'static>) {
    let expire = Duration::seconds(0);
    let session = base_cookie(SESSION_COOKIE_NAME, String::new(), true, secure, expire);
    let csrf = base_cookie(CSRF_COOKIE_NAME, String::new(), false, secure, expire);
    (session, csrf)
}

#[cfg(test)]
mod tests {
    use super::*;

    // `requires_csrf_check`/`csrf_matches`'s own unit tests moved with them to
    // `metap_runtime::cookie_auth` — not duplicated here.

    fn headers_from(pairs: &[(&str, &str)]) -> axum::http::HeaderMap {
        let mut headers = axum::http::HeaderMap::new();
        for (name, value) in pairs {
            headers.insert(
                axum::http::HeaderName::from_bytes(name.as_bytes()).unwrap(),
                value.parse().unwrap(),
            );
        }
        headers
    }

    /// Audit 04 A#4: `GET /auth/token` mints a Bearer JWT, so it is gated even though `GET` is
    /// otherwise CSRF-exempt — but only for a caller authenticating by cookie.
    #[test]
    fn a_cookie_authenticated_credential_request_needs_the_csrf_header() {
        let cookie = format!("{SESSION_COOKIE_NAME}=jwt; {CSRF_COOKIE_NAME}=abc");
        assert!(!credential_issuing_request_allowed(&headers_from(&[(
            "cookie", &cookie
        )])));
        assert!(!credential_issuing_request_allowed(&headers_from(&[
            ("cookie", &cookie),
            (CSRF_HEADER_NAME, "wrong"),
        ])));
        assert!(credential_issuing_request_allowed(&headers_from(&[
            ("cookie", &cookie),
            (CSRF_HEADER_NAME, "abc"),
        ])));
    }

    /// Precedence must match `crate::auth::AuthContext`'s: a Bearer caller is never CSRF-gated,
    /// even when a cookie happens to ride along on the same request.
    #[test]
    fn a_bearer_caller_is_never_gated_here() {
        let cookie = format!("{SESSION_COOKIE_NAME}=jwt; {CSRF_COOKIE_NAME}=abc");
        assert!(credential_issuing_request_allowed(&headers_from(&[
            ("authorization", "Bearer token"),
            ("cookie", &cookie),
        ])));
    }

    /// No credential at all is `AuthContext`'s job to reject, not this gate's — returning `false`
    /// here would turn a plain 401 "unauthorized" into a confusing "invalid CSRF token".
    #[test]
    fn a_request_with_no_credential_at_all_is_left_to_the_extractor() {
        assert!(credential_issuing_request_allowed(&headers_from(&[])));
    }

    #[test]
    fn session_cookie_is_http_only_and_csrf_cookie_is_readable_by_script() {
        let (session, csrf) = session_cookies("jwt-value", "csrf-value", 3600, true);
        assert_eq!(session.name(), SESSION_COOKIE_NAME);
        assert_eq!(session.value(), "jwt-value");
        assert_eq!(session.http_only(), Some(true), "the JWT must never be script-readable");
        assert_eq!(csrf.name(), CSRF_COOKIE_NAME);
        assert_eq!(
            csrf.http_only(),
            Some(false),
            "same-origin script must be able to read this to echo it back"
        );
        for cookie in [&session, &csrf] {
            assert_eq!(cookie.path(), Some("/"));
            assert_eq!(cookie.secure(), Some(true));
            assert_eq!(cookie.same_site(), Some(SameSite::Lax));
            assert_eq!(cookie.max_age(), Some(Duration::seconds(3600)));
        }
    }

    #[test]
    fn secure_flag_is_threaded_through_for_local_http_development() {
        let (session, csrf) = session_cookies("jwt", "csrf", 60, false);
        assert_eq!(session.secure(), Some(false));
        assert_eq!(csrf.secure(), Some(false));
    }

    /// A cleared cookie must keep every attribute the original was set with, or the browser files
    /// it as a *different* cookie and the real one survives logout — see `clear_session_cookies`'s
    /// own doc comment.
    #[test]
    fn clearing_expires_immediately_and_keeps_the_original_attributes() {
        let (session, csrf) = clear_session_cookies(true);
        for cookie in [&session, &csrf] {
            assert_eq!(cookie.max_age(), Some(Duration::seconds(0)));
            assert_eq!(cookie.path(), Some("/"));
            assert_eq!(cookie.secure(), Some(true));
            assert_eq!(cookie.same_site(), Some(SameSite::Lax));
            assert_eq!(cookie.value(), "");
        }
        assert_eq!(session.http_only(), Some(true));
        assert_eq!(csrf.http_only(), Some(false));
    }
}
