[package]
name = "metap-graphql"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-crud = { path = "../metap-crud" }
metap-metadata = { path = "../metap-metadata" }
metap-permission = { path = "../metap-permission" }
metap-query = { path = "../metap-query" }
anyhow.workspace = true
async-graphql = { workspace = true, features = ["dataloader"] }
async-trait.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt"] }
uuid.workspace = true

[dev-dependencies]
arc-swap.workspace = true
metap-control = { path = "../metap-control" }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
