[package]
name = "metap"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-app = { path = "../metap-app" }
metap-attachments = { path = "../metap-attachments" }
metap-auth = { path = "../metap-auth" }
metap-cache = { path = "../metap-cache" }
metap-config = { path = "../metap-config" }
metap-control = { path = "../metap-control" }
metap-cron = { path = "../metap-cron" }
metap-crud = { path = "../metap-crud" }
metap-dashboards = { path = "../metap-dashboards" }
metap-graphql = { path = "../metap-graphql" }
metap-graphql-http = { path = "../metap-graphql-http" }
metap-grpc = { path = "../metap-grpc" }
metap-http = { path = "../metap-http" }
metap-infra = { path = "../metap-infra" }
metap-jwks = { path = "../metap-jwks" }
metap-jwks-http = { path = "../metap-jwks-http" }
metap-metadata = { path = "../metap-metadata" }
metap-peripherals = { path = "../metap-peripherals" }
metap-permission = { path = "../metap-permission" }
metap-query = { path = "../metap-query" }
metap-reconciler = { path = "../metap-reconciler" }
metap-runtime = { path = "../metap-runtime" }
metap-storage = { path = "../metap-storage" }
metap-workflow = { path = "../metap-workflow" }
