[package]
name = "metap"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-auth = { path = "../metap-auth" }
metap-cache = { path = "../metap-cache" }
metap-control = { path = "../metap-control" }
metap-control-http = { path = "../metap-control-http" }
metap-crud = { path = "../metap-crud" }
metap-http = { path = "../metap-http" }
metap-infra = { path = "../metap-infra" }
metap-lowcode = { path = "../metap-lowcode" }
metap-lowcode-http = { path = "../metap-lowcode-http" }
metap-metadata = { path = "../metap-metadata" }
metap-peripherals = { path = "../metap-peripherals" }
metap-permission = { path = "../metap-permission" }
metap-query = { path = "../metap-query" }
metap-workflow = { path = "../metap-workflow" }
