[package]
name = "metap-crud"
version = "0.1.0"
edition.workspace = true

[dependencies]
metap-control = { path = "../metap-control" }
metap-metadata = { path = "../metap-metadata" }
metap-permission = { path = "../metap-permission" }
metap-query = { path = "../metap-query" }
metap-workflow = { path = "../metap-workflow" }
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "chrono",
  "json",
] }
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
