[package]
name = "metap-control"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
metap-infra = { path = "../metap-infra" }
metap-peripherals = { path = "../metap-peripherals" }
metap-permission = { path = "../metap-permission" }
moka.workspace = true
secrecy.workspace = true
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-rustls",
  "postgres",
  "uuid",
  "chrono",
  "json",
  "migrate",
  "macros",
] }
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true
uuid.workspace = true
vaultrs = "0.7"
serde.workspace = true
serde_json.workspace = true
aws-sdk-secretsmanager = { version = "1.114.0", default-features = false, features = ["default-https-client", "rt-tokio"] }
google-cloud-secretmanager-v1 = "1.13.0"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
